version: 2
updates:
  - package-ecosystem: npm
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    schedule:
      interval: monthly
    versioning-strategy: increase

  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2
