name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      BUILD_PATH: ${{ vars.BUILD_PATH || '.' }}
      SITE_URL: ${{ vars.SITE_URL }}
      BASE_PATH: ${{ vars.BASE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/${{ env.BUILD_PATH }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/${{ env.BUILD_PATH }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager" >&2
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile }}

      # ===== Astro image/asset cache (default: node_modules/.astro) =====
      - name: Restore Astro cache
        id: astro-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_PATH }}/node_modules/.astro
          key: ${{ runner.os }}-astro-cache-v3-${{ hashFiles('**/astro.config.*','**/package-lock.json','**/pnpm-lock.yaml','**/yarn.lock','public/**/*.{png,jpg,jpeg,webp,avif,gif,svg}','src/assets/**/*.{png,jpg,jpeg,webp,avif,gif,svg}','content/**/*.{png,jpg,jpeg,webp,avif,gif,svg}') }}
          restore-keys: |
            ${{ runner.os }}-astro-cache-v3-

      # ===== /content cache keyed by content/meta.json (source commit) =====
      - name: Restore content cache
        id: content-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_PATH }}/content
          key: ${{ runner.os }}-content-v5-${{ hashFiles('content/meta.json') }}-primary
          restore-keys: |
            ${{ runner.os }}-content-v5-${{ hashFiles('content/meta.json') }}-
            ${{ runner.os }}-content-v5-

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: ${{ env.BUILD_PATH }}

      # Always run; import should reuse restored files and fetch only updates
      - name: Fetch data
        run: npm run import
        working-directory: ${{ env.BUILD_PATH }}
        env:
          STADIA_MAPS_API_KEY: ${{ secrets.STADIA_MAPS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Save refreshed /content with a unique key to avoid collisions
      - name: Save content cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_PATH }}/content
          key: ${{ runner.os }}-content-v5-${{ hashFiles('content/meta.json') }}-${{ github.run_id }}

      - name: Print env
        run: |
          echo "vars.SITE_URL='${{ vars.SITE_URL }}'"
          echo "env SITE_URL='$SITE_URL'"
          echo "env BASE_PATH='$BASE_PATH'"

      - name: Build with Astro
        run: ${{ steps.detect-package-manager.outputs.runner }} astro build
        working-directory: ${{ env.BUILD_PATH }}
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          BASE_PATH: ${{ vars.BASE_PATH }}

      # Save Astro cache only if we missed on restore
      - name: Save Astro cache (on miss)
        if: steps.astro-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_PATH }}/node_modules/.astro
          key: ${{ runner.os }}-astro-cache-v3-${{ hashFiles('**/astro.config.*','**/package-lock.json','**/pnpm-lock.yaml','**/yarn.lock','public/**/*.{png,jpg,jpeg,webp,avif,gif,svg}','src/assets/**/*.{png,jpg,jpeg,webp,avif,gif,svg}','content/**/*.{png,jpg,jpeg,webp,avif,gif,svg}') }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
